# Generated by Django 6.0.1 on 2026-01-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="naam")),
                ("notes", models.TextField(blank=True, verbose_name="notities")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="bijgewerkt op"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.location",
                        verbose_name="bovenliggende locatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "locatie",
                "verbose_name_plural": "locaties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        help_text="Uniek identificatienummer, bijv. HVAC-01",
                        max_length=50,
                        unique=True,
                        verbose_name="objectnummer",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="naam")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hvac", "HVAC / Klimaat"),
                            ("electrical", "Elektrisch"),
                            ("plumbing", "Sanitair"),
                            ("safety", "Veiligheid"),
                            ("av", "Audio/Video"),
                            ("furniture", "Meubilair"),
                            ("building", "Gebouw"),
                            ("other", "Overig"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="categorie",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="fabrikant"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=200, verbose_name="model"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="serienummer"
                    ),
                ),
                (
                    "install_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="installatiedatum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operationeel"),
                            ("attention", "Aandacht Nodig"),
                            ("out_of_service", "Buiten Gebruik"),
                            ("disposed", "Afgevoerd"),
                        ],
                        default="operational",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Laag"),
                            ("medium", "Middel"),
                            ("high", "Hoog"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="kritiekheid",
                    ),
                ),
                (
                    "warranty_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="garantie tot"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="assets/", verbose_name="foto"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="omschrijving"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="bijgewerkt op"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="core.location",
                        verbose_name="locatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "object",
                "verbose_name_plural": "objecten",
                "ordering": ["asset_tag"],
            },
        ),
    ]
