# Generated by Django 6.0.1 on 2026-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_monument",
            field=models.BooleanField(
                default=False,
                help_text="Dit object valt onder monumentenzorg",
                verbose_name="rijksmonument",
            ),
        ),
    ]
