# Generated by Django 6.0.1 on 2026-01-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_is_monument"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="last_maintenance_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="laatste onderhoud"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="maintenance_interval_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Aantal dagen tussen onderhoudsbeurten",
                null=True,
                verbose_name="onderhoudsinterval (dagen)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="maintenance_notes",
            field=models.TextField(
                blank=True,
                help_text="Wat moet er gedaan worden bij onderhoud?",
                verbose_name="onderhoudsinstructies",
            ),
        ),
    ]
