# Generated by Django 6.0.1 on 2026-01-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_maintenance_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Bijv. "Filter vervangen", "Jaarlijkse inspectie"',
                        max_length=200,
                        verbose_name="onderhoudstaak",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        help_text="Aantal dagen tussen onderhoudsbeurten",
                        verbose_name="interval (dagen)",
                    ),
                ),
                (
                    "last_performed",
                    models.DateField(
                        blank=True, null=True, verbose_name="laatst uitgevoerd"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Wat moet er gedaan worden?",
                        verbose_name="instructies",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_schedules",
                        to="core.asset",
                        verbose_name="object",
                    ),
                ),
            ],
            options={
                "verbose_name": "onderhoudsschema",
                "verbose_name_plural": "onderhoudsschema's",
                "ordering": ["asset", "name"],
            },
        ),
    ]
