# Generated by Django 6.0.1 on 2026-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_maintenance_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="replacement_date",
            field=models.DateField(
                blank=True,
                help_text="Datum waarop dit object vervangen moet worden",
                null=True,
                verbose_name="geplande vervanging",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="replacement_notes",
            field=models.TextField(
                blank=True,
                help_text="Reden voor vervanging, specificaties voor nieuw object, etc.",
                verbose_name="vervangingsnotities",
            ),
        ),
    ]
