# Generated by Django 6.0.1 on 2026-01-25 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="Gebruiker moet wachtwoord wijzigen bij volgende login",
                        verbose_name="wachtwoord wijzigen verplicht",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gebruiker",
                    ),
                ),
            ],
            options={
                "verbose_name": "gebruikersprofiel",
                "verbose_name_plural": "gebruikersprofielen",
            },
        ),
    ]
