# Generated by Django 6.0.1 on 2026-01-26 09:20

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_userprofile"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mailadres"),
                ),
                (
                    "token",
                    models.CharField(
                        default=accounts.models.generate_token,
                        max_length=64,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Uitstaand"),
                            ("accepted", "Geaccepteerd"),
                            ("expired", "Verlopen"),
                            ("cancelled", "Geannuleerd"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="persoonlijk bericht"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="aangemaakt"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geaccepteerd op"
                    ),
                ),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="geaccepteerd door",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Groep waar de gebruiker aan wordt toegevoegd",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="groep",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uitgenodigd door",
                    ),
                ),
            ],
            options={
                "verbose_name": "uitnodiging",
                "verbose_name_plural": "uitnodigingen",
                "ordering": ["-created_at"],
            },
        ),
    ]
