# Generated by Django 6.0.1 on 2026-01-25 12:17

import django.db.models.deletion
import requests.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepairRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titel")),
                ("description", models.TextField(verbose_name="omschrijving")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Laag"),
                            ("normal", "Normaal"),
                            ("high", "Hoog"),
                            ("urgent", "Spoed"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="prioriteit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nieuw"),
                            ("triaged", "Getriageerd"),
                            ("in_progress", "Bezig"),
                            ("waiting", "Wacht"),
                            ("completed", "Gereed"),
                            ("closed", "Gesloten"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(max_length=200, verbose_name="naam melder"),
                ),
                (
                    "requester_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mailadres"
                    ),
                ),
                (
                    "requester_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefoonnummer"
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True,
                        choices=[("email", "E-mail"), ("phone", "Telefoon")],
                        default="email",
                        max_length=10,
                        verbose_name="voorkeur contact",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="streefdatum"),
                ),
                (
                    "resolution_summary",
                    models.TextField(blank=True, verbose_name="oplossing"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="afgesloten op"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="bijgewerkt op"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_requests",
                        to="core.asset",
                        verbose_name="object/installatie",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="toegewezen aan",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_requests",
                        to="core.location",
                        verbose_name="locatie",
                    ),
                ),
                (
                    "requester_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ingediend door",
                    ),
                ),
                (
                    "triaged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triaged_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="getriageerd door",
                    ),
                ),
            ],
            options={
                "verbose_name": "reparatieverzoek",
                "verbose_name_plural": "reparatieverzoeken",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_triage", "Kan verzoeken triageren"),
                    ("can_assign", "Kan verzoeken toewijzen"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=requests.models.attachment_path,
                        verbose_name="bestand",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="geüpload op"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="geüpload door",
                    ),
                ),
                (
                    "repair_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="requests.repairrequest",
                        verbose_name="reparatieverzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "bijlage",
                "verbose_name_plural": "bijlagen",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("note", "Notitie"),
                            ("status_change", "Statuswijziging"),
                            ("assignment", "Toewijzing"),
                            ("time_spent", "Tijdsbesteding"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("note", models.TextField(verbose_name="notitie")),
                (
                    "minutes_spent",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="minuten besteed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "repair_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to="requests.repairrequest",
                        verbose_name="reparatieverzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "logboekregel",
                "verbose_name_plural": "logboekregels",
                "ordering": ["-created_at"],
            },
        ),
    ]
