# Generated by Django 6.0.1 on 2026-01-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_repairrequest_estimated_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="repairrequest",
            name="actual_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Werkelijke kosten in euro's",
                max_digits=10,
                null=True,
                verbose_name="werkelijke kosten",
            ),
        ),
    ]
