# Generated by Django 6.0.1 on 2026-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0003_add_actual_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("created", "Nieuw"),
                    ("note", "Notitie"),
                    ("status_change", "Statuswijziging"),
                    ("assignment", "Toewijzing"),
                    ("time_spent", "Tijdsbesteding"),
                ],
                default="note",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
