# Generated by Django 6.0.1 on 2026-01-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0004_alter_worklog_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="repairrequest",
            name="po_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="inkoopordernummer"
            ),
        ),
        migrations.AddField(
            model_name="repairrequest",
            name="quote_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="offertebedrag",
            ),
        ),
        migrations.AddField(
            model_name="repairrequest",
            name="quote_status",
            field=models.CharField(
                choices=[
                    ("none", "Geen"),
                    ("requested", "Aangevraagd"),
                    ("received", "Ontvangen"),
                    ("approved", "Goedgekeurd"),
                ],
                default="none",
                max_length=15,
                verbose_name="offertestatus",
            ),
        ),
        migrations.AddField(
            model_name="repairrequest",
            name="vendor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="leverancier"
            ),
        ),
    ]
