# Generated by Django 6.0.1 on 2026-01-25 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0005_add_procurement_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("mention", "Vermelding"),
                            ("assignment", "Toewijzing"),
                            ("status_change", "Statuswijziging"),
                        ],
                        default="mention",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titel")),
                ("message", models.TextField(verbose_name="bericht")),
                ("is_read", models.BooleanField(default=False, verbose_name="gelezen")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "repair_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="requests.repairrequest",
                        verbose_name="reparatieverzoek",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gebruiker",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificatie",
                "verbose_name_plural": "notificaties",
                "ordering": ["-created_at"],
            },
        ),
    ]
