# Generated by Django 6.0.1 on 2026-01-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0006_add_notification_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="titel"),
        ),
    ]
