# Generated by Django 5.2.10 on 2026-02-06 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0007_add_attachment_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repairrequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verwijderd op"
            ),
        ),
        migrations.AddField(
            model_name="repairrequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="verwijderd door",
            ),
        ),
        migrations.AddField(
            model_name="repairrequest",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="verwijderd"),
        ),
    ]
